name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-leaflet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install react-scripts
      run: npm install -g react-scripts

    - name: Clone from assembla
      env:
        USERNAME: ${{ secrets.ASSEMBLA_USER_NAME }}
        PASSWORD: ${{ secrets.ASSEMBLA_API_SECRET }}
      run: git clone "https://$USERNAME:$PASSWORD@git.assembla.com/troyweb/bechtel.echartmobile.git"

    - name: Checkout develop branch
      working-directory: bechtel.echartmobile
      run: git checkout fastlane

    ## Install Leaflet Dependencies
    - name: Cache Leaflet Node Modules
      uses: actions/cache@v1
      env:
        cache-name: cache-leaflet-node-modules
      with:
        path: bechtel.echartmobile/nuclide_leaflet/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('bechtel.echartmobile/nuclide_leaflet/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Install leaflet dependencies
      working-directory: bechtel.echartmobile/nuclide_leaflet
      run: npm install

    - name: Compile mobile app
      env:
        CI: ""
      working-directory: bechtel.echartmobile/nuclide_leaflet
      run: npm run build:mobile

    - name: Archive Leaflet Build
      uses: actions/upload-artifact@v1
      with:
        name: leaflet-build
        path: bechtel.echartmobile/nuclide_leaflet/build


  build-ios:
    runs-on: macOS-latest
    needs: build-leaflet
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Clone from assembla
      env:
        USERNAME: ${{ secrets.ASSEMBLA_USER_NAME }}
        PASSWORD: ${{ secrets.ASSEMBLA_API_SECRET }}
      run: git clone "https://$USERNAME:$PASSWORD@git.assembla.com/troyweb/bechtel.echartmobile.git"

    - name: Checkout develop branch
      working-directory: bechtel.echartmobile
      run: git checkout fastlane

    - name: Download Leaflet Build
      uses: actions/download-artifact@v1
      with:
        name: leaflet-build
        path: bechtel.echartmobile/www

    ## Install Root Dependencies
    - name: Cache Root Node Modules
      uses: actions/cache@v1
      env:
        cache-name: cache-root-node-modules
      with:
        path: bechtel.echartmobile/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('bechtel.echartmobile/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Install root dependencies
      working-directory: bechtel.echartmobile
      run: npm install

    - name: Install Cordova
      run: npm install -g cordova

    # https://stackoverflow.com/a/46823492/10680786
    - name: Build mobile app with cordova
      working-directory: bechtel.echartmobile
      run: |
        cordova platform add ios
        sed -i "" "s/iPhone Distribution/iPhone Developer/g" platforms/ios/cordova/build-release.xcconfig
        #    cordova build

    - name: Create Appfile
      env:
        FASTLANE_APPFILE_TESTFLIGHT: ${{ secrets.FASTLANE_APPFILE_TESTFLIGHT }}
      working-directory: bechtel.echartmobile/fastlane
      run: echo $FASTLANE_APPFILE_TESTFLIGHT > Appfile

    - name: Install pod dependencies
      working-directory: bechtel.echartmobile/platforms/ios
      run: pod install

    - name: Build with fastlane
      env:
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      working-directory: bechtel.echartmobile
      run: fastlane ios beta

    - name: Deploy to testflight with fastlane
      env:
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      working-directory: bechtel.echartmobile
      run: fastlane ios upload
