name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
  FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
  FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
  FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
  MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_SECRET }}

jobs:
  build-leaflet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install react-scripts
      run: npm install -g react-scripts

    - name: Clone from assembla
      env:
        USERNAME: ${{ secrets.ASSEMBLA_USER_NAME }}
        PASSWORD: ${{ secrets.ASSEMBLA_API_SECRET }}
      run: git clone "https://$USERNAME:$PASSWORD@git.assembla.com/troyweb/bechtel.echartmobile.git"

    - name: Checkout develop branch
      working-directory: bechtel.echartmobile
      run: git checkout fastlane

    ## Install Leaflet Dependencies
    - name: Cache Leaflet Node Modules
      uses: actions/cache@v1
      env:
        cache-name: cache-leaflet-node-modules
      with:
        path: bechtel.echartmobile/nuclide_leaflet/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('bechtel.echartmobile/nuclide_leaflet/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Install leaflet dependencies
      working-directory: bechtel.echartmobile/nuclide_leaflet
      run: npm install

    - name: Compile mobile app
      env:
        CI: ""
      working-directory: bechtel.echartmobile/nuclide_leaflet
      run: npm run build:mobile

    - name: Archive Leaflet Build
      uses: actions/upload-artifact@v1
      with:
        name: leaflet-build
        path: bechtel.echartmobile/nuclide_leaflet/build


  build-ios:
    runs-on: macOS-latest
    needs: build-leaflet
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - uses: webfactory/ssh-agent@v0.2.0
      with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
                  
    - name: Clone from assembla
      env:
        USERNAME: ${{ secrets.ASSEMBLA_USER_NAME }}
        PASSWORD: ${{ secrets.ASSEMBLA_API_SECRET }}
      run: git clone "https://$USERNAME:$PASSWORD@git.assembla.com/troyweb/bechtel.echartmobile.git"

    - name: Checkout develop branch
      working-directory: bechtel.echartmobile
      run: git checkout fastlane

    - name: Download Leaflet Build
      uses: actions/download-artifact@v1
      with:
        name: leaflet-build
        path: bechtel.echartmobile/www

    ## Install Root Dependencies
    - name: Cache Root Node Modules
      uses: actions/cache@v1
      env:
        cache-name: cache-root-node-modules
      with:
        path: bechtel.echartmobile/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('bechtel.echartmobile/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Install root dependencies
      working-directory: bechtel.echartmobile
      run: npm install

    - name: Install Cordova
      run: npm install -g cordova

    - name: Add iOS platform to cordova
      env:
        FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
      working-directory: bechtel.echartmobile
      run: |
        cordova platform add ios

    - name: Create Appfile
      env:
        FASTLANE_APPFILE_TESTFLIGHT: ${{ secrets.FASTLANE_APPFILE_TESTFLIGHT }}
      working-directory: bechtel.echartmobile/fastlane
      run: echo $FASTLANE_APPFILE_TESTFLIGHT > Appfile
               
    - name: Make Provisioning Profiles directory
      run: mkdir -pv ~/Library/MobileDevice/Provisioning\ Profiles/
      
    - name: Build with fastlane
      working-directory: bechtel.echartmobile
      env:
        CORDOVA_BUILD_JSON: ${{ secrets.CORDOVA_BUILD_JSON }}
      run: |
        echo $CORDOVA_BUILD_JSON > build.json
        fastlane ios beta

    - name: Deploy to testflight with fastlane
      working-directory: bechtel.echartmobile
      run: fastlane ios upload
