name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name : Install Fastlane
      run:
        brew install fastlane

    # Clone from assembla
    - name: Clone from assembla
      env:
        USERNAME: ${{ secrets.ASSEMBLA_USER_NAME }}
        PASSWORD: ${{ secrets.ASSEMBLA_API_SECRET }}
      run: git clone "https://$USERNAME:$PASSWORD@git.assembla.com/troyweb/bechtel.echartmobile.git"

    - name: Checkout develop branch
      run: |
        cd bechtel.echartmobile
        git checkout fastlane

    - name: Install root dependencies
      run: |
        cd bechtel.echartmobile
        npm install -g cordova
        npm install

    - name: Install react-scripts
      run: npm install -g react-scripts

    - name: Install npm dependencies
      run: |
        cd bechtel.echartmobile/nuclide_leaflet
        npm install

    - name: Compile mobile app
      env:
        CI: ""
      run: |
        cd bechtel.echartmobile/nuclide_leaflet
        npm run build:mobile

    # https://stackoverflow.com/a/46823492/10680786
    - name: Build mobile app with cordova
      run: |
        cd bechtel.echartmobile
        cordova platform add ios
        sed -i "" "s/iPhone Distribution/iPhone Developer/g" platforms/ios/cordova/build-release.xcconfig
        cordova build

    - name: Copy fastlane folder to platforms/ios
      env:
        FASTLANE_APPFILE_TESTFLIGHT: ${{ secrets.FASTLANE_APPFILE_TESTFLIGHT }}
      run: |
        #        cd bechtel.echartmobile
        #        cp -r fastlane platforms/ios/
        echo $FASTLANE_APPFILE_TESTFLIGHT > fastlane/Appfile

    - name: Install pod dependencies
      run: |
        cd bechtel.echartmobile/platforms/ios
        pod install

    - name: Build with fastlane
      run: |
        cd bechtel.echartmobile/platforms/ios
        fastlane ios beta

    - name: Deploy to testflight with fastlane
      run: |
        cd bechtel.echartmobile/platforms/ios
        fastlane ios upload

