name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clone from assembla
      env:
        USERNAME: ${{ secrets.ASSEMBLA_USER_NAME }}
        PASSWORD: ${{ secrets.ASSEMBLA_API_SECRET }}
      run: git clone "https://$USERNAME:$PASSWORD@git.assembla.com/troyweb/bechtel.echartmobile.git"

    - name: Checkout develop branch
      working-directory: bechtel.echartmobile
      run: git checkout fastlane

    - name: Upload Project
      uses: actions/upload-artifact@v1
      with:
        name: project
        path: bechtel.echartmobile

  root-dependencies:
    runs-on: ubuntu-latest
    needs: clone
    steps:
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Download project
      uses: actions/download-artifact@v1
      with:
        name: project

    - name: Cache Root Node Modules
      uses: actions/cache@v1
      env:
        cache-name: cache-root-node-modules
      with:
        path: bechtel.echartmobile/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('bechtel.echartmobile/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Install root dependencies
      working-directory: bechtel.echartmobile
      run: npm install

    - name: Upload Root Dependencies
      uses: actions/upload-artifact@v1
      with:
        name: root-dependencies
        path: bechtel.echartmobile/node_modules

  leaflet-dependencies:
    runs-on: ubuntu-latest
    needs: clone
    steps:
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Download project
      uses: actions/download-artifact@v1
      with:
        name: project

    - name: Cache Leaflet Node Modules
      uses: actions/cache@v1
      env:
        cache-name: cache-leaflet-node-modules
      with:
        path: bechtel.echartmobile/nuclide_leaflet/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('bechtel.echartmobile/nuclide_leaflet/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-


    - name: Install leaflet dependencies
      working-directory: bechtel.echartmobile/nuclide_leaflet
      run: npm install

    - name: Upload Leaflet Dependencies
      uses: actions/upload-artifact@v1
      with:
        name: leaflet-dependencies
        path: bechtel.echartmobile/nuclide_leaflet/node_modules

  build:
    needs: [root-dependencies, leaflet-dependencies]
    runs-on: macOS-latest

    steps:
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install Fastlane
      run: brew install fastlane

    - name: Install Cordova
      run: npm install -g cordova

    - name: Install react-scripts
      run: npm install -g react-scripts

    - name: Download project
      uses: actions/download-artifact@v1
      with:
        name: project

    - name: Download Root Dependencies
      uses: actions/download-artifact@v1
      with:
        name: root-dependencies

    - name: Download Leaflet Dependencies
      uses: actions/download-artifact@v1
      with:
        name: leaflet-dependencies

    - name: Compile mobile app
      env:
        CI: ""
      working-directory: bechtel.echartmobile/nuclide_leaflet
      run: npm run build:mobile

    # https://stackoverflow.com/a/46823492/10680786
    - name: Build mobile app with cordova
      working-directory: bechtel.echartmobile
      run: |
        cordova platform add ios
        sed -i "" "s/iPhone Distribution/iPhone Developer/g" platforms/ios/cordova/build-release.xcconfig
        cordova build

    - name: Copy fastlane folder to platforms/ios
      env:
        FASTLANE_APPFILE_TESTFLIGHT: ${{ secrets.FASTLANE_APPFILE_TESTFLIGHT }}
      working-directory: bechtel.echartmobile
      run: |
        #        cp -r fastlane platforms/ios/
        echo $FASTLANE_APPFILE_TESTFLIGHT > fastlane/Appfile
        ## Show me the appfile
        cat fastlane/Appfile

    - name: Install pod dependencies
      working-directory: bechtel.echartmobile/platforms/ios
      run: pod install

    - name: Build with fastlane
      working-directory: bechtel.echartmobile
      run: fastlane ios beta

    - name: Deploy to testflight with fastlane
      working-directory: bechtel.echartmobile
      run: fastlane ios upload
