name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
        
    # Clone from assembla
    - name: Clone from assembla
      env:
        USERNAME: ${{ secrets.ASSEMBLA_USER_NAME }}
        PASSWORD: ${{ secrets.ASSEMBLA_API_SECRET }}
      run: git clone "https://$USERNAME:$PASSWORD@git.assembla.com/troyweb/bechtel.echartmobile.git"

    - name: Checkout develop branch
      run: |
        cd bechtel.echartmobile
        git checkout develop
    
    - name: Install root dependencies
      run: |
        cd bechtel.echartmobile
        npm install -g cordova
        npm install

    - name: Install react-scripts
      run: npm install -g react-scripts

    - name: Install npm dependencies
      run: |
        cd bechtel.echartmobile/nuclide_leaflet
        npm install
        
    - name: Compile mobile app
      env:
        CI: ""
      run: |
        cd bechtel.echartmobile/nuclide_leaflet
        npm run build:mobile
        
    - name: Build mobile app with cordova
      run: |
        cd bechtel.echartmobile
        cordova platform add ios
        cordova build

    - name: Install pod dependencies
      run: |
        cd bechtel.echartmobile/platforms/ios
        pod install
        
    - name: Setup provisioning profile
      run: |
        chmod +x .github/secrets/decrypt_secrets.sh
        ./.github/secrets/decrypt_secrets.sh
      env:
        IOS_PROFILE_KEY: ${{ secrets.IOS_PROFILE_KEY }}
    
    - name: Clean project build folder
      run: |
        cd bechtel.echartmobile/platforms/ios
        xcodebuild clean -project Chart\ of\ the\ Nuclides.xcodeproj -scheme Chart\ of\ the\ Nuclides
    
    - name: Archive App
      env: 
        DEVELOPMENT_TEAM: ${{ secrets.TEAM_ID }}
      run: |
          cd bechtel.echartmobile/platforms/ios
          xcodebuild archive \
            -project Chart\ of\ the\ Nuclides.xcodeproj \
            -scheme Chart\ of\ the\ Nuclides \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/Chart\ of\ the\ Nuclides.xcarchive
        
    - name: Create ipa
      env: 
        DEVELOPMENT_TEAM: ${{ secrets.TEAM_ID }}
      run: |
        cd bechtel.echartmobile/platforms/ios
        xcodebuild -exportArchive \
          -archivePath ./Chart\ of\ the\ Nuclides.xcarchive \
          -exportOptionsPlist exportOptions.plist \
          -exportPath exportPath -allowProvisioningUpdates
        
