name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
        
    # Clone from assembla
    - name: Clone from assembla
      env:
        USERNAME: ${{ secrets.ASSEMBLA_USER_NAME }}
        PASSWORD: ${{ secrets.ASSEMBLA_API_SECRET }}
      run: git clone "https://$USERNAME:$PASSWORD@git.assembla.com/troyweb/bechtel.echartmobile.git"

    - name: Checkout develop branch
      run: |
        cd bechtel.echartmobile
        git checkout develop

    - name: Install npm dependencies
      run: |
        cd bechtel.echartmobile/nuclide_leaflet
        npm run build:mobile
        
